### PR TITLE
Assorted tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
@phillipj @Trott: I could split the patches if it helps, but this was easier. You can check the individual patches to make review easier.

Note that:

1. I didn't drop Node.js 6.x support, but we might as well do that here
2. The repo lacks linting, but I wasn't sure which ruleset to use, so I thought I'd leave this for someone else

### CODE REVIEW

**Comment by XhmikosR** [comment]
BTW it seems Travis CI isn't enabled for the repo?

**Comment by phillipj** [comment]
Thanks!

You mention the lack of linting and that someone else should look at that, but at the same time seem to include a lot of formatting changes. Not sure I understand the rationale here, mind elaborating?

**Comment by XhmikosR** [comment]
Well, I don't have the time to make all the changes myself ;)

So, I just made use of xo to find ES6-related issues. To make review easier just check the non-whitespace diff.

You can only decide which linting tool and rules should be used. :)

**Comment by phillipj** [comment]
Aha, thx for the explanation 👍

**Comment by XhmikosR** [comment]
Alright, I reverted the style changes in most places. The diff should be cleaner now.

Can you at least enable Travis for the repo? I can add linting later if you tell me which tool/rules to use.

**Comment by phillipj** [comment]
> Can you at least enable Travis for the repo? I can add linting later if you tell me which tool/rules to use.

I was just trying to figure out why Travis *isn't* kicking off, as my Travis CI configuration surely gives the impression it should be activated in this repo 🤔 

Screenshot 2019-09-12 at 13 35 00

**Comment by XhmikosR** [comment]
Hmm, that looks like the .com Travis CI instance.

You should remove the app and re-add it in the repo.

**Comment by phillipj** [comment]
Ooooh good catch! I'll re-install it 🤞

**Comment by phillipj** [comment]
Sadly that didn't work as expected either, so gave up and enabled GitHub Actions instead: https://github.com/phillipj/metalsmith-yearly-pagination/commit/1ebef79052a72230370ea3e29ec24e18d084f12a

**Comment by XhmikosR** [comment]
Cool, I'll tweak that too and push here.

**Comment by XhmikosR** [comment]
@phillipj: can you remove any Travis CI hooks/integrations from the repo?

**Comment by phillipj** [comment]
Sure, done ✔️

**Comment by XhmikosR** [comment]
OK, this is ready from my side.

Linting and dropping Node.js 6.x support can be done later.

**Comment by phillipj** [comment]
Awesome, thanks a lot for doing some much needed chores here! 💯

**Comment by XhmikosR** [comment]
This shouldn't have been squashed, though.

**Comment by phillipj** [comment]
Alrighty, next time you got strong preferences for not squashing, please be explicit about it.

I personally thought there was a couple of too small commits which wasn't very valuable on their own, whilst some other could surely have been left off as their own.

Looking back at the last force push you did seconds before me merging the branch, I do see you cleaned up (and removed) the small commits I had in mind. Sorry I didn't notice that as I was writing the squash commit message whilst you were also busy fixing the commit history.

**Comment by XhmikosR** [comment]
Yeah, I always keep my commits as separate patches.

No worries, we'll get it right the next time.

Can you release a new patch version with the changes so far, or do you want to wait until we tackle the other issues?

**Comment by phillipj** [comment]
As I always prefer to be overly careful about semver, I bumped major version since Node.js 4 is no longer supported.

v3.0.0 just got published 🚀

**Comment by XhmikosR** [comment]
We could probably drop Node.js 6.x too then.

Anyway, please check the other 2 issues and let me know how to proceed.

**Pull request merged**
