### PR TITLE
Update test.yml

### PR DESCRIPTION
**Pull request by XhmikosR**
Switch to `actions/setup-node@v1`

### CODE REVIEW

**Comment by phillipj** [comment]
Cool. Why? ...so I know for later & other projects :)

**Comment by XhmikosR** [comment]
Just updating to the latest v1 action tag :)

**Comment by phillipj** [comment]
Ohh so this is in fact an upgrade to a v1.x kind of tag? I totally misread this to be a downgrade from v1.1 -> v1.0.

**Comment by XhmikosR** [comment]
Yeah, it's a newer tag. They have deprecated `version`.

**Pull request merged**
